name: Build Android App

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Grant workflow permission to create releases and upload assets
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clear gradle wrapper cache
      run: |
        rm -rf ~/.gradle/wrapper/dists
        rm -rf ~/.gradle/caches

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '11.0'
        accept-android-sdk-licenses: true

    - name: Build with Gradle
      run: ./gradlew clean assembleDebug --no-daemon -Dorg.gradle.java.home=$JAVA_HOME

    - name: Upload APKs to existing release 'Apps'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd app/build/outputs/apk/debug
        gh release upload Apps *.apk --repo BiniFn/Novara --clobber
